server:
  port: 9191
  tomcat:
    accept-count: 1000
  servlet:
    context-path: /eBao
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebao?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  resources:
#    static-locations: classpath:/templates/,/classpath:/static/
  thymeleaf:
    cache: false
    prefix:
      classpath: /templates/,/static/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    encoding: utf-8
    suffix: .html
    mode: HTML5
mybatis:
  mapper-locations: mapper/*.xml

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


# 上传的服务器上的映射文件夹


file:
  path: F:/img/
#虚拟路径
  static-path: /upload/image/**
  #访问文件的基本路径地址
  base-url: http://127.0.0.1:9191/eBao/upload/image/
