server:
  port: 9191
  tomcat:
    accept-count: 1000
  servlet:
    context-path: /eBao

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebao?serverTimezone=GMT%2B8
    data-username: root
    data-password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: mapper/*.xml

