server:
  port: 9191
  tomcat:
    accept-count: 1000
  servlet:
    context-path: /eBao
  jdbc:mysql://localhost:3306/ebao?serverTimezone=UTC
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebao?serverTimezone=UTC
    username: root
    password: 111
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: mapper/*.xml

