server:
  port: 9191
  tomcat:
    accept-count: 1000
  servlet:
    context-path: /eBao
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebao?serverTimezone=UTC
    username: root
    password: 123wswj,
    driver-class-name: com.mysql.cj.jdbc.Driver
#  resources:
#    static-locations: classpath:/static/
#  mvc:
#    static-path-pattern: /**
  thymeleaf:
    cache: false
    prefix:
      classpath: /templates/
mybatis:
  mapper-locations: mapper/*.xml


